export {
  createRequestLatencyTrace,
  withRequestLatencyTrace,
  measureLatencyPhase,
  recordRequestQuery,
  type RequestLatencyTrace,
} from './request-latency.js';
export {
  createPostgresDb,
  withUnpairedDeviceFence,
  migrateToLatest,
  holdPostgresControlPlaneLock,
  isPostgresConnectionClassError,
  CONTROL_PLANE_RECONNECT_BUDGET_MS,
  CONTROL_PLANE_RECONNECT_INTERVAL_MS,
  PostgresAdvisoryLockHeldError,
  PostgresControlPlaneGenerationTakenError,
  PostgresControlPlaneUnreachableError,
  SchemaGenerationAheadError,
  type ControlPlaneGenerationProof,
  type MigrateOptions,
  type PostgresAdvisoryLock,
  type PostgresControlPlaneFence,
  type PostgresControlPlaneLockOptions,
} from './db.js';
export {
  IntegrationStore,
  integrationImportCodes,
  type IntegrationImportDiagnostic,
  type IntegrationAccount,
  type IntegrationSource,
  type IntegrationEvent,
  type IntegrationEventKind,
  type IntegrationSourceStatus,
} from './integrations.js';
// NOTE: `createEmbeddedDb` (pglite) is deliberately NOT exported here. pglite is
// a devDependency and must stay out of every production import graph; the test
// harness reaches it through `@verity/store/testing`.
export {
  EventStore,
  SESSION_AUTOMATION_MAX_CONSECUTIVE_ERRORS,
  type EventSink,
  RUNNER_FRAME_PROTOCOL_VERSION,
  type RunnerFrameIngest,
  type RunnerFrameIngestResult,
  type AttachmentBlob,
  type SequencedEvent,
  type SessionProjectionFacts,
  type SessionEventStats,
  type SessionRecord,
  type SessionPlanning,
  type SessionSlideDeckRecord,
  type SessionWorkspaceFileRecord,
  type SessionGmailConnection,
  type SessionCalendarConnection,
  type SessionContactsConnection,
  type GoogleWorkspaceFileKind,
  type GoogleSlideImageCleanupRecord,
  type SessionInput,
  type RunningTurnRecord,
  type QueuedTurnRecord,
  type QueuedTurnInput,
  type ProjectRecord,
  type VeritySettingsPatch,
  type VeritySettingsRecord,
  type ProjectSettingsPatch,
  type ProjectSettingsRecord,
  type HttpMcpConnectionRecord,
  type ProjectMcpBindingRecord,
  type DevServerRecord,
  type DevServerCreateInput,
  type DevServerPatch,
  type DevServerDetectionStateRecord,
  type PublicPreviewShareRecord,
  type PublicPreviewShareCreateInput,
  type PublicPreviewShareState,
  type ClaudeEgressCaRecord,
  type ClaudeEgressClientCertRecord,
  DEV_SERVER_HOST_PORT_RANGES,
  DeletedProjectError,
  DevServerPortRangeExhaustedError,
  PROJECT_MEMORY_MAX_CHARS,
  ProjectMemoryTooLargeError,
  type ProjectUpsertInput,
  type ProjectReleaseStatus,
  type ProjectState,
  type ProjectKind,
  LOCAL_PROJECT_OWNER,
  isLocalProject,
  isSessionLinkProject,
  isInstallationPlaceholder,
  ProjectIdentityClaimConflict,
  type SessionAutomationRecord,
  type SessionAutomationStatus,
  type SessionAutomationInput,
  SessionAutomationWorkspaceChangedError,
  type SessionAutomationOutcome,
  type SecretKeyMetaRecord,
  type AuthTokenRecord,
  type DevicePushTokenRecord,
  type PushReceiptRecord,
} from './store.js';
export { TranscriptStore } from './transcript.js';
export {
  ManagedDevServerStore,
  ManagedDevServerConflictError,
  ManagedDevServerInputError,
  ManagedDevServerPortsFullError,
  managedDevServerNameKey,
  normalizeManagedDevServerWorkdir,
  type ManagedDevServerRecord,
  type ManagedDevServerInstanceRecord,
  type ManagedDevServerDesired,
  type ManagedDevServerState,
  type ManagedDevServerInstancePatch,
} from './managed-dev-servers.js';
export {
  TaskStore,
  TaskNotFoundError,
  TaskRevisionConflictError,
  TaskInputError,
  TASK_STATUSES,
  OPEN_TASK_STATUSES,
  TASK_TITLE_MAX,
  TASK_DETAIL_MAX,
  TASK_RESULT_MAX,
  TASK_ATTACHMENTS_MAX,
  type TaskRecord,
  type TaskInput,
  type TaskPatch,
  type TaskListFilter,
  type TaskAttachment,
  type TaskOrigin,
  type TaskStatus,
} from './tasks.js';
export {
  LiveMeetingStore,
  type LiveMeetingSyncRecord,
  type LiveMeetingNoteSyncRecord,
  type LiveMeetingInsight,
} from './live-meetings.js';
export {
  migrationProvider,
  latestMigrationKey,
  earliestMigrationKey,
  schemaCompatibilityWindow,
  type SchemaCompatibilityWindow,
  getExecutedMigrations,
  executedSchemaGeneration,
} from './migrations.js';
export { computeNextRun, validateSchedule, MIN_INTERVAL_MINUTES } from './schedule.js';
export {
  type SecretCipher,
  type SealableSecretCipher,
  createSecretCipher,
  createPassthroughCipher,
  createSealableSecretCipher,
  isEncrypted,
  SealedError,
} from './crypto.js';
export {
  deriveKeyFromPassword,
  generateSalt,
  createKeyVerifier,
  keyMatchesVerifier,
} from './secret-key.js';
export type {
  Database,
  EventsTable,
  SessionsTable,
  TranscriptLinesTable,
  QueuedTurnsTable,
  QueuedTurnOpts,
  VeritySettingsTable,
  ProjectSettingsTable,
  HttpMcpConnectionsTable,
  ProjectMcpBindingsTable,
  SecretKeyMetaTable,
  AuthTokenTable,
  DevicePushTokensTable,
  ProjectsTable,
  SessionBackendStateTable,
  SessionAutomationsTable,
  SecretRunGrantsTable,
  SecretApprovalsTable,
  SecretRevocationsTable,
  DevServerDetectionStateTable,
  PublicPreviewSharesTable,
  UplinkPendingShareRemovalsTable,
  ScheduleConfig,
} from './schema.js';

export * from './knowledge.js';

export * from './knowledge-sources.js';
