// AUTO-GENERATED by scripts/stamp-mobile-build-info.mjs — do not edit by hand.
//
// Committed with null placeholders; overwritten in CI before Metro exports an OTA
// bundle (see .github/workflows/mobile-ota.yml). The native build keeps these
// placeholders and displays its app.config.ts marketing version; each OTA export
// replaces RELEASE_VERSION with the exact patch allocated by the workflow.
export const BUILD_COMMIT = 'dev';
export const RELEASE_VERSION: string | null = null;
