import { type Href, router } from 'expo-router';
import { Pressable, Text, View } from 'react-native';
import { StyleSheet } from 'react-native-unistyles';

import {
  attentionActionLabel,
  attentionNoticeText,
  type AttentionAction,
  type AttentionNotice,
} from '@verity/mobile';

/**
 * Where each remedy lives in THIS app. A total record rather than a chain of
 * comparisons, so adding an action to the shared vocabulary without giving it a
 * screen here is a compile error instead of a button that silently never renders.
 *
 * That check is on the KEYS. The route itself is asserted, as every other route
 * constant in this app is (`onboarding/welcome.tsx`, `unlock-device.tsx`): typed
 * routes are generated by the dev server, so CI typechecks without them and no
 * `Href` here is worth more than the test that walks this exact string into the
 * settings screen's params.
 */
export const ATTENTION_ACTION_ROUTES: Readonly<Record<AttentionAction, Href>> = {
  'codex-login': '/settings?agentLogin=codex' as Href,
};

/**
 * A server-level condition you have to act on — sealed at-rest encryption, an
 * Updater that stopped answering, a Codex sign-in the gateway is refusing.
 * Modelled on the overview's stale banner but deliberately without its retry:
 * unlike a failed poll, none of these is fixed by asking again.
 *
 * What some of them ARE fixed by is one screen, and only the server knows which —
 * so when it names an action the banner offers it as a tap. Signing in again is
 * otherwise four taps into Settings that the sentence has to describe rather than
 * open, and the condition it fixes (Codex refusing every model call) is the one
 * where the wait costs the most.
 */
export function ServerAttentionBanner({ notice }: { notice: AttentionNotice }) {
  const action = notice.action;
  return (
    <View style={styles.banner}>
      {/* Three lines, not the stale banner's one: these sentences name a
          consequence as well as a cause, and the refusal shares its row with the
          action button. Clipping this one would drop the half that says what to
          do about it. */}
      <Text style={styles.bannerText} numberOfLines={3} accessibilityRole="alert">
        {attentionNoticeText(notice)}
      </Text>
      {action === undefined ? null : (
        <Pressable
          // `navigate`, not `push`: the banner stays on screen for as long as the
          // condition holds, and a second tap should return to the sign-in screen
          // rather than stack another copy of it behind the first.
          onPress={() => router.navigate(ATTENTION_ACTION_ROUTES[action])}
          accessibilityRole="button"
          accessibilityLabel={attentionActionLabel(action)}
          hitSlop={8}
          style={styles.bannerAction}
        >
          <Text style={styles.bannerRetry}>{attentionActionLabel(action)}</Text>
        </Pressable>
      )}
    </View>
  );
}

/**
 * The overview's other banner: a poll that failed while a list is already on
 * screen. Kept in this file rather than the screen's, because it and
 * {@link ServerAttentionBanner} are the same strip of chrome and drift the moment
 * their styles are written down twice.
 */
export function StaleBanner({ message, onRetry }: { message: string; onRetry: () => void }) {
  return (
    <View style={styles.banner}>
      <Text style={styles.bannerText} numberOfLines={1}>
        Couldn&apos;t refresh — {message}
      </Text>
      <Pressable onPress={onRetry} accessibilityRole="button" hitSlop={8}>
        <Text style={styles.bannerRetry}>Retry</Text>
      </Pressable>
    </View>
  );
}

const styles = StyleSheet.create((theme) => ({
  banner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: theme.spacing.md,
    paddingHorizontal: theme.spacing.lg,
    paddingVertical: theme.spacing.sm,
    backgroundColor: theme.colors.surfaceAlt,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
  },
  bannerText: {
    flex: 1,
    color: theme.colors.tone.attention,
    fontSize: theme.text.xs,
  },
  bannerAction: {
    // On the PRESSABLE, which is the row's flex child — the label inside it is not,
    // so pinning this there would have left the sizing to whatever the wrapper did.
    // React Native already defaults to 0; it is written down because the affordance
    // is the one thing that must not give way. "Sign in to Codex" is several times
    // the width of "Retry", and the text beside it is `flex: 1` over three lines.
    flexShrink: 0,
  },
  bannerRetry: {
    color: theme.colors.primary,
    fontSize: theme.text.xs,
    fontWeight: '600',
  },
}));
