import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import mobileConfig from '../app.config';
type SceneManifest = {
  UIApplicationSceneManifest: {
    UIApplicationSupportsMultipleScenes: boolean;
    UISceneConfigurations: {
      UIWindowSceneSessionRoleApplication: { UISceneDelegateClassName: string }[];
    };
  };
};
type Mod<T> = (config: {
  modResults: T;
  modRequest: { nextMod: (value: unknown) => Promise<unknown> };
}) => Promise<{ modResults: T }>;
type PluginResult = {
  mods: {
    ios: {
      appDelegate: Mod<{ language: string; contents: string }>;
      infoPlist: Mod<Partial<SceneManifest>>;
    };
  };
};
// xcode's UUID dependency is ESM; no Xcode IDs are generated by these two mods.
jest.mock('uuid', () => ({ v4: () => 'scene-lifecycle-test' }));
const plugin = require('../plugins/withSceneLifecycle.js') as {
  (config: unknown): PluginResult;
};
// SDK 57 bare-minimum AppDelegate, captured from expo/expo's sdk-57 template.
const template = readFileSync(resolve(__dirname, './fixtures/Expo57AppDelegate.swift'), 'utf8');

async function generate(contents = template) {
  const config = plugin({ ...mobileConfig });
  const base = { ...config, modRequest: { nextMod: async (value: unknown) => value } };
  const app = await config.mods.ios.appDelegate({
    ...base,
    modResults: { language: 'swift', contents },
  });
  const plist = await config.mods.ios.infoPlist({ ...base, modResults: {} });
  return { swift: app.modResults.contents, plist: plist.modResults };
}

describe('iOS scene lifecycle', () => {
  it('registers the migration in the actual app config', () => {
    // A plugin that works in isolation still ships the launch trap if omitted from CNG.
    expect(mobileConfig.plugins).toContain('./plugins/withSceneLifecycle');
  });

  it('connects the declared scene to a scene-owned window and starts React only there', async () => {
    const { swift, plist } = await generate();
    const manifest = plist.UIApplicationSceneManifest!;
    expect(manifest.UIApplicationSupportsMultipleScenes).toBe(false);
    const declared =
      manifest.UISceneConfigurations.UIWindowSceneSessionRoleApplication[0].UISceneDelegateClassName.split(
        '.',
      ).at(-1);
    expect(swift).toContain(`class ${declared}: UIResponder, UIWindowSceneDelegate`);
    const [app, scene] = swift.split(`class ${declared}:`);
    expect(app).not.toContain('startReactNative(');
    expect(swift).not.toContain('UIWindow(frame:');
    expect(scene).toContain('UIWindow(windowScene: windowScene)');
    expect(scene).toContain('appDelegate.window = window');
    expect(scene.match(/startReactNative\(/g)).toHaveLength(1);
    expect(app).toContain(
      'super.application(application, didFinishLaunchingWithOptions: launchOptions)',
    );
  });

  it('preserves cold links, warm links and Expo lifecycle callbacks', async () => {
    const { swift } = await generate();
    expect(swift).toContain('sceneLaunchOptions = launchOptions');
    expect(swift).toContain('launchOptions[.url] = context.url');
    expect(swift).toContain('launchOptions[.userActivityDictionary]');
    expect(swift).toContain('launchOptions[.remoteNotification]');
    expect(swift).toContain('open: context.url, options: options');
    expect(swift).toContain('continue: userActivity, restorationHandler:');
    for (const callback of [
      'DidBecomeActive',
      'WillResignActive',
      'WillEnterForeground',
      'DidEnterBackground',
    ]) {
      expect(swift).toContain(`?.application${callback}(UIApplication.shared)`);
    }
  });

  // The silent failure: iOS launches Verity without a scene to deliver a watch
  // recording, React Native never starts, and nobody receives the file.
  it('activates the watch inbox at launch, outside the scene', async () => {
    const native = readFileSync(resolve(__dirname, '../native/VerityWatchInbox.swift'), 'utf8');
    const inbox = native.match(/final class (\w+): NSObject, WCSessionDelegate/)?.[1];
    expect(inbox).toBeDefined();
    expect(native).toContain('static let shared');
    const { swift } = await generate();
    const launch = swift.slice(
      swift.indexOf('didFinishLaunchingWithOptions launchOptions'),
      swift.indexOf('return super.application(application, didFinishLaunchingWithOptions'),
    );
    expect(launch).toContain(`${inbox}.shared.activate()`);
  });

  // A killed final attempt otherwise leaves the watch waiting until retention expires.
  it('finishes an interrupted exhausted watch transcription before retention cleanup', () => {
    const native = readFileSync(resolve(__dirname, '../native/VerityWatchInbox.swift'), 'utf8');
    const exhausted = native.slice(
      native.indexOf('} else if (entry.attempts ?? 0) >= Self.maxAttempts {'),
      native.indexOf('} else if entry.lastAttemptAt'),
    );
    expect(exhausted).toMatch(/if entry.state == \.received \{\s*finish\(/);
    expect(exhausted).toContain('.failure(NSError(');
    expect(exhausted.indexOf('finish(')).toBeLessThan(exhausted.indexOf('if expired'));
    const finish = native.slice(native.indexOf('private func finish('));
    expect(finish).toMatch(/case \.failure\(let error\):\s*entry.state = \.failed/);
    expect(finish).toContain('try save(entry)');
    expect(finish).toMatch(
      /if entry.state == \.transcribed \|\| \(entry.attempts \?\? 0\) >= Self.maxAttempts \{\s*self.reply\(reply\)/,
    );
  });

  // A terminal reply deletes the watch copy, so persistence must succeed first.
  it('persists a watch transcript before releasing either audio copy', () => {
    const native = readFileSync(resolve(__dirname, '../native/VerityWatchInbox.swift'), 'utf8');
    const finish = native.slice(
      native.indexOf('private func finish('),
      native.indexOf('private static func transcribeFile('),
    );
    const saved = finish.indexOf('try save(entry)');
    expect(saved).toBeGreaterThan(-1);
    expect(saved).toBeLessThan(finish.indexOf('removeItem(at: audioURL(id))'));
    expect(saved).toBeLessThan(finish.indexOf('self.reply(reply)'));
    expect(finish.slice(saved)).toMatch(/catch \{[^}]*return\s*\}/);
  });

  it('is idempotent and rejects template drift rather than retaining legacy startup', async () => {
    const { swift } = await generate();
    expect((await generate(swift)).swift).toBe(swift);
    await expect(
      generate(template.replace('factory.startReactNative(', 'factory.boot(')),
    ).rejects.toThrow('startup changed');
  });
});
