import { readFileSync } from 'node:fs';

import { describe, expect, it } from 'vitest';

/**
 * The committed bundle, read as text. Read from the path the build script
 * declares rather than a copy of it, so moving the artifact moves this guard
 * with it instead of leaving it asserting about a file nobody writes anymore.
 */
const outfile = /outfile = '([^']+)'/u.exec(
  readFileSync('scripts/build-runner-worker.mjs', 'utf8'),
)?.[1];

describe('the committed runner worker bundle', () => {
  it('names no module by where npm happened to install it', () => {
    expect(outfile, 'scripts/build-runner-worker.mjs no longer declares an outfile').toBeDefined();
    const bundle = readFileSync(outfile as string, 'utf8');

    // esbuild labels each bundled module with the path it was read from, in a
    // `// path` comment and again in the `__commonJS` key below it. npm decides
    // per install whether a dependency is hoisted to the repository root or
    // nested under `packages/<name>/node_modules`, so those labels differ
    // between two installs of the identical tree — and `--check` then calls a
    // bundle that is byte-identical everywhere it matters out of date. The
    // failure is silent in the other direction too: a bundle regenerated by a
    // build script that stopped normalizing is reproducible only on the machine
    // that produced it, and CI says so about whichever layout it did not get.
    const labels = bundle.match(/^(?:\/\/ |\s*")[^"\s]*node_modules\/[^"\s]*/gmu) ?? [];
    expect(labels.length, 'the bundle names no third-party module at all').toBeGreaterThan(0);

    const layoutBound = labels.filter((label) =>
      // Anything before the first `node_modules/` is the path to the install
      // root. A second one further along the path is a real dependency of a
      // dependency and belongs in the label.
      /^(?:\/\/ |\s*")[^"\s]+\/node_modules\//u.test(label),
    );
    expect(layoutBound, 'module labels still carry their install location').toEqual([]);
  });
});
