import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

type LockPackage = {
  version?: string;
  resolved?: string;
  license?: string;
  link?: boolean;
};

type PackageLock = {
  packages?: Record<string, LockPackage>;
};

const repositoryRoot = resolve(import.meta.dirname, '..');
const lockPath = resolve(repositoryRoot, 'package-lock.json');
const noticesPath = resolve(repositoryRoot, 'THIRD_PARTY_NOTICES.md');
const legacyLicenseOverrides = new Map([['exit@0.1.2', 'MIT']]);

function packageName(path: string): string {
  const marker = 'node_modules/';
  const tail = path.slice(path.lastIndexOf(marker) + marker.length);
  const parts = tail.split('/');
  return tail.startsWith('@') ? parts.slice(0, 2).join('/') : parts[0]!;
}

function sourceUrl(name: string, version: string, resolved?: string): string {
  if (resolved?.startsWith('https://registry.npmjs.org/')) return resolved;
  return `https://www.npmjs.com/package/${encodeURIComponent(name)}/v/${encodeURIComponent(version)}`;
}

function render(lock: PackageLock): string {
  const packages = new Map<
    string,
    { name: string; version: string; license: string; source: string }
  >();
  for (const [path, metadata] of Object.entries(lock.packages ?? {})) {
    if (!path.includes('node_modules/') || metadata.link === true || metadata.version === undefined)
      continue;
    const name = packageName(path);
    const key = `${name}@${metadata.version}`;
    const license = metadata.license ?? legacyLicenseOverrides.get(key);
    if (license === undefined) {
      throw new Error(`dependency ${key} has no license metadata or reviewed override`);
    }
    const candidate = {
      name,
      version: metadata.version,
      license,
      source: sourceUrl(name, metadata.version, metadata.resolved),
    };
    const existing = packages.get(key);
    if (existing !== undefined && existing.license !== license) {
      throw new Error(
        `dependency ${key} has conflicting licenses: ${existing.license} / ${license}`,
      );
    }
    packages.set(key, candidate);
  }

  const rows = [...packages.values()].sort((a, b) =>
    `${a.name}\0${a.version}`.localeCompare(`${b.name}\0${b.version}`, 'en'),
  );
  const counts = new Map<string, number>();
  for (const row of rows) counts.set(row.license, (counts.get(row.license) ?? 0) + 1);
  const summary = [...counts.entries()]
    .sort(([a], [b]) => a.localeCompare(b, 'en'))
    .map(([license, count]) => `| ${license} | ${count} |`)
    .join('\n');
  const inventory = rows
    .map(
      ({ name, version, license, source }) =>
        `| ${name.replaceAll('|', '\\|')} | ${version} | ${license.replaceAll('|', '\\|')} | [source](${source}) |`,
    )
    .join('\n');

  return `# Third-party notices

This file inventories the npm packages pinned by \`package-lock.json\`. It is
generated by \`node scripts/third-party-notices.ts --write\`; edit the generator
or dependency metadata rather than this file. License expressions are the
publishers' package metadata and do not replace the license texts shipped in
their source archives or installed packages.

Verity itself is licensed under Apache-2.0. The Verity name and marks are governed
separately by \`TRADEMARKS.md\`.

## Reviewed non-code material

- Material Symbols is supplied by \`@expo-google-fonts/material-symbols\`; its
  package code is MIT and its bundled font files are Apache-2.0.
- The product website requests Inter from Google Fonts at runtime. Inter is
  licensed under the SIL Open Font License 1.1 and is not stored in this source
  tree.
- Product screenshots and Verity artwork in this repository are project-authored.
  Their source availability does not grant trademark rights; see
  \`TRADEMARKS.md\`.

## Packages with separate or reciprocal terms

- \`@anthropic-ai/claude-agent-sdk\` and its platform packages are distributed
  under Anthropic's published legal terms rather than an SPDX open-source
  license. They are optional agent tooling, not relicensed by Verity. See
  <https://code.claude.com/docs/en/legal-and-compliance>.
- \`lightningcss\` and its platform packages are MPL-2.0.
- \`caniuse-lite\` includes data under CC-BY-4.0.
- \`argparse\` declares Python-2.0.
- \`node-forge\` offers BSD-3-Clause or GPL-2.0; Verity uses the BSD option.

## License summary

| Declared license | Package/version pairs |
| --- | ---: |
${summary}

## Complete npm inventory

| Package | Version | Declared license | Source archive |
| --- | --- | --- | --- |
${inventory}
`;
}

const mode = process.argv[2];
if (mode !== '--check' && mode !== '--write') {
  throw new Error('usage: third-party-notices.ts --check | --write');
}
const expected = render(JSON.parse(await readFile(lockPath, 'utf8')) as PackageLock);
if (mode === '--write') {
  await writeFile(noticesPath, expected);
} else {
  const actual = await readFile(noticesPath, 'utf8').catch(() => '');
  if (actual !== expected) {
    throw new Error('THIRD_PARTY_NOTICES.md is stale; run npm run licenses:write');
  }
}
