import { StyleSheet } from 'react-native-unistyles';
export const styles = StyleSheet.create((theme) => ({
  screen: { flex: 1, backgroundColor: theme.colors.background },
  content: { padding: 16, gap: 12 },
  group: { gap: 8 },
  knowledgeSplit: { flexDirection: 'row', alignItems: 'flex-start', gap: 24 },
  knowledgeMasterPane: {
    width: 360,
    flexShrink: 0,
    gap: 8,
    paddingRight: 16,
    borderRightWidth: 1,
    borderColor: theme.colors.border,
  },
  knowledgeDetailPane: { flex: 1, minWidth: 0 },
  knowledgeDetailAction: { marginLeft: 384, maxWidth: 720 },
  row: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 8 },
  text: { color: theme.colors.text, fontSize: 16, lineHeight: 24 },
  muted: { color: theme.colors.textMuted, fontSize: 13 },
  heading: { color: theme.colors.text, fontSize: 20, fontWeight: '600' },
  bold: { fontWeight: '700' },
  code: { fontFamily: 'monospace', backgroundColor: theme.colors.surface },
  cell: { flex: 1, minWidth: 70 },
  button: {
    minHeight: 44,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 8,
    borderRadius: 6,
  },
  buttonText: { color: theme.colors.text, fontSize: 13 },
  iconButton: { width: 44, paddingHorizontal: 0 },
  explorerRow: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingRight: 8,
  },
  explorerToggle: {
    width: 28,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  explorerEntry: {
    flex: 1,
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  selectedRow: { backgroundColor: theme.colors.surface, borderRadius: 6 },
  entryText: { color: theme.colors.text, fontSize: 14, flex: 1 },
  toolbar: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderColor: theme.colors.border,
  },
  menuBackdrop: {
    flex: 1,
    justifyContent: 'flex-end',
    padding: 16,
    backgroundColor: 'rgba(0,0,0,0.35)',
  },
  menuCard: {
    gap: 8,
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.surface,
  },
  input: {
    color: theme.colors.text,
    padding: 12,
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 8,
    minHeight: 44,
  },
  editor: { minHeight: 240, textAlignVertical: 'top', fontFamily: 'monospace' },
  error: { color: theme.colors.text, backgroundColor: theme.colors.surface, padding: 12 },
}));
